backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "places"
    label: "Places Collection"
    folder: "src/pages/places"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Preview Image", name: "previewImage", widget: image }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          fields: [{ label: "Image", name: "image", widget: image }],
        }
  - name: "people"
    label: "People Collection"
    folder: "src/pages/people"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Preview Image", name: "previewImage", widget: image }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          fields: [{ label: "Image", name: "image", widget: image }],
        }
  - name: "events"
    label: "Events Collection"
    folder: "src/pages/events"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Preview Image", name: "previewImage", widget: image }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          fields: [{ label: "Image", name: "image", widget: image }],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Main"
        name: "main"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery-page",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields: [{ label: "Image", name: "image", widget: image }],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery-page",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields: [{ label: "Image", name: "image", widget: image }],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
